- type: department
  id: StalkerRF
  color: "#9FED58"
  name: department-rf
  description: department-Stalker-description
  weight: 10
  roles:
  - ChechnyaRFRPK
  - ChechnyaRFAKC
  - ChechnyaRFAKCY
  - ChechnyaRFMedic
  - ChechnyaRFSpec

- type: department
  id: StalkerCRI
  name: department-cri
  description: department-StalkerBrigands-description
  color: "#111111"
  weight: 8
  roles:
  - ChechnyaCRIRPK
  - ChechnyaCRIAKC
  - ChechnyaCRIAKCY
  - ChechnyaCRIMedic
  - ChechnyaCRISpec
